name: autofix.ci

on:
  push: { branches: [main] }
  pull_request: {}

permissions: {}

concurrency: { group: "autofix-${{ github.ref }}", cancel-in-progress: true }

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: unjs/setup-jup@85aa1e9e4cd2995fba3bee414cde74bf88637a2c # v1.0.0
      - run: pnpm fmt
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with: { commit-message: "chore: apply automated updates" }
